services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5050
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - backend
    command: sh -c "npm install && npm run vite -- --host"

volumes:
  node_modules: