services:
  core:
    build:
      context: ./gcs-core
      dockerfile: Dockerfile
    volumes:
      - ./gcs-core:/app
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5050
  
  ui:
    build:
      context: ./gcs-ui
      dockerfile: Dockerfile
    volumes:
      - ./gcs-ui:/app
      - node_modules:/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - core
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  node_modules: